# Generated by Django 4.0.5 on 2022-06-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contents',
            field=models.CharField(default='', max_length=200),
        ),
    ]
