# Generated by Django 4.0.5 on 2022-06-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contents',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
