# Generated by Django 4.0.5 on 2022-06-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contents',
        ),
    ]
